apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: celery
  name: celery-controller
  namespace: redis
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: taskQueue
        component: celery
    spec:
      containers:
      - image: sahandha/celery-redis 
        name: celery
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
