apiVersion: v1
kind: Service
metadata:
  labels:
    component: flower
  name: flower-redis
  namespace: redis
spec:
  ports:
  - port: 5555
  selector:
    app: taskQueue
    component: flower
  type: LoadBalancer
