apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: redis
  name: redis-controller
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
